dnastring = 'ATTGATACCCTCAGGTTATAGGGATGACAATAGTTTCACTAGTCTACATAGTATCAAGACTGTCGGGGCTGCGCTTCGGGAGACGACTATTTACCCACGGGGGTTAAGTCTCTGGCGAATTTAAAGTCGCCCCCCGTCCGGGGCCGGGGATCTACACAAATCTCCTGCTAGTTCGCCTACTGCGAAAGTCTGCGGCTCGTACTTAGCATCATTATCGCATCCGCACGTACAAGATCCAGTTGCTGGAACACATTAGGACACGGAACCAAGTTGTCCCGGGAGGAGGGGTATGGCGAGCGATACTTAGTAAACCTCAGAACGCACCTCGGTAAGCACTATTGCATACCATGCGTTCACCTCAGAATCCTCCCCGGCCTCGCCCGTTACCGCCCGCAGGGTCCTGTTACACACAGAAGAACGAGAGAGCGCTATACAATGTTCGTTGTGACTTCTTTGATTTCGTTATCTGTTCTGAACGTACGAACCTTAGATAAGTGTAGAGTTTATAGCCTCCGCGTCTAATCACGGACATACTCATGCCCCTGCGGGCGAAACAATTACCCATTTGCATGGGTGGCTTCTTTTGGTTTTTAGCGAACACTGTCGAGACGACCTTAGACCCACTACAACTTGTGCAAGGCGGCTGAAATGTTTGGGAAGCGACATGCGGGAGGGTTCCGCTACATTATCCTCAGTGAAATTCGTTGTCTGCTATATGTAGGGGCTCAGATCAAGGTGTTGGGCTAGACCTATGGTGTCGGGTTACTCGACCCTTCGGGCGTATCACATGAGCCCACGTGCCTAGAATCAATCAAGAACTAATGTATAAACCATACCTACTCAGGGATCTAGGGAGTTCACCCCGCAGACGCTAGATAGGGACCTTGGAGTGGCGACATTTTAAAAACCGTTTCTTTGTCCGGCCAA'
(a, c, g, t) = (0, 0, 0, 0)
for base in dnastring:
    if base == 'A':
        a += 1
    if base == 'C':
        c += 1
    if base == 'G':
        g += 1
    if base == 'T':
        t += 1

print(a, c, g, t)
