def find_substrings(s, t):
    locations = []
    for i in range(len(s)-len(t)):
        if large[i:(i+len(t))] == t:
            locations.append(i+1)
    return locations
        

large = 'CAAAGGTACAAAGGTCGCGTGGTTGCAAAGGTCAAAGGTAAGAGCAATAAACGAACAAAGGTCCCAAAGGTGCCCAAAGGTCCAAAGGTCAAAGGTAAAGAACTCCCAAAGGTATACGCAAAGGTCAAAGGTCCGAGCTGCCATGCGTCAAAGGTGATCCAAAGGTAGCAAAGGTTCAAAGGTACAAAGGTACAAAGGTCAAAGGTCAAAGGTTCAAAGGTAAGACCAAAGGTTGGACCAAAGGTTCAAAGGTACCAAAGGTGAAACAAAGGTACAAAGGTGTGCCTAGCTCGATCGACAGCAAAGGTACAAAGGTTCTACCAAAGGTCAAAGGTGGATCAAAGGTAATAATCAAAGGTGAGTTTCAAAGGTAAGGTTTTCAAAGGTCACAAAGGTGCAAAGGTAAACTCAAAGGTCCAAAGGTAATTCAAAGGTCGCTACCCATCGGCAAAGGTAACAACAAAGGTGTAATCAAAGGTCACAAAGGTGCCAAAGGTTCAAAGGTCAAAGGTCAAAGGTTTCTCGCCCCAAAGGTCAAAGGTTACAAGCAACTACAAAGGTCAAAGGTCCATCGTAGGCAAAGGTATGCAAAGGTACGACAAAGGTTGCCACCAAAGGTGGTCCTATCAAAGGTCAAAGGTCAAAGGTTCCAAAGGTCAAAGGTCAAAGGTTCAAAGGTCAAAGGTCGTACAAAGGTGGGTCAAAGGTGTGCAAAGGTGGTGTCTTCGATCAAAGGTCACCAAAGGTATACCCAAAGGTCAAAGGTAATAACAAAGGTTAACAAAGGTTAGCAAAGGTCTGACAAAGGTCAAAGGTCAAAGGTGGTACAACAAAGGTTGTGCCAAAGGTCTATATGCAAAGGTGGTCAAAGGTGTTACTGTCAAAGGTTCGCTTGGGGTTCAAAGGTCAGCAAAGGTGCGGAACAAAGGT'
small = 'CAAAGGTCA'

loc = find_substrings(large, small)
for idx in loc:
    print(idx, end = ' ')
